name: 'Build, Test & Deploy'

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install pre-commit

      - run: pre-commit run --all-files

      - run: pip install -r requirements.txt -t ./package

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Serverless Framework & its plugins
        run: npm i --no-package-lock

      - name: Deploy to Scaleway Functions
        run: npx serverless deploy --verbose
        env:
          # Scaleway secrets for function deployment
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_REGION: ${{ secrets.SCW_DEFAULT_REGION }}
          SCW_DEFAULT_ZONE: ${{ secrets.SCW_DEFAULT_ZONE }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}

          # TGTG secrets for app configuration via serverless.yaml
          TGTG_ACCESS_TOKEN: ${{ secrets.TGTG_ACCESS_TOKEN }}
          TGTG_REFRESH_TOKEN: ${{ secrets.TGTG_REFRESH_TOKEN }}
          TGTG_USER_ID: ${{ secrets.TGTG_USER_ID }}
          TGTG_COOKIE: ${{ secrets.TGTG_COOKIE }}

          # TELEGRAM secrets
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          # non-secret env vars
          TGTG_ITEM_IDS: ${{ vars.TGTG_ITEM_IDS }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
